const gitFollowers= [
    {
        "login": "sean-birmingham",
        "id": 39016563,
        "node_id": "MDQ6VXNlcjM5MDE2NTYz",
        "avatar_url": "https://avatars3.githubusercontent.com/u/39016563?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sean-birmingham",
        "html_url": "https://github.com/sean-birmingham",
        "followers_url": "https://api.github.com/users/sean-birmingham/followers",
        "following_url": "https://api.github.com/users/sean-birmingham/following{/other_user}",
        "gists_url": "https://api.github.com/users/sean-birmingham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sean-birmingham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sean-birmingham/subscriptions",
        "organizations_url": "https://api.github.com/users/sean-birmingham/orgs",
        "repos_url": "https://api.github.com/users/sean-birmingham/repos",
        "events_url": "https://api.github.com/users/sean-birmingham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sean-birmingham/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Nelson-Singleton",
        "id": 67346445,
        "node_id": "MDQ6VXNlcjY3MzQ2NDQ1",
        "avatar_url": "https://avatars2.githubusercontent.com/u/67346445?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Nelson-Singleton",
        "html_url": "https://github.com/Nelson-Singleton",
        "followers_url": "https://api.github.com/users/Nelson-Singleton/followers",
        "following_url": "https://api.github.com/users/Nelson-Singleton/following{/other_user}",
        "gists_url": "https://api.github.com/users/Nelson-Singleton/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Nelson-Singleton/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Nelson-Singleton/subscriptions",
        "organizations_url": "https://api.github.com/users/Nelson-Singleton/orgs",
        "repos_url": "https://api.github.com/users/Nelson-Singleton/repos",
        "events_url": "https://api.github.com/users/Nelson-Singleton/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Nelson-Singleton/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "ericagirges",
        "id": 65200891,
        "node_id": "MDQ6VXNlcjY1MjAwODkx",
        "avatar_url": "https://avatars0.githubusercontent.com/u/65200891?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ericagirges",
        "html_url": "https://github.com/ericagirges",
        "followers_url": "https://api.github.com/users/ericagirges/followers",
        "following_url": "https://api.github.com/users/ericagirges/following{/other_user}",
        "gists_url": "https://api.github.com/users/ericagirges/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ericagirges/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ericagirges/subscriptions",
        "organizations_url": "https://api.github.com/users/ericagirges/orgs",
        "repos_url": "https://api.github.com/users/ericagirges/repos",
        "events_url": "https://api.github.com/users/ericagirges/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ericagirges/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "chrisjcorbin",
        "id": 64340122,
        "node_id": "MDQ6VXNlcjY0MzQwMTIy",
        "avatar_url": "https://avatars2.githubusercontent.com/u/64340122?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/chrisjcorbin",
        "html_url": "https://github.com/chrisjcorbin",
        "followers_url": "https://api.github.com/users/chrisjcorbin/followers",
        "following_url": "https://api.github.com/users/chrisjcorbin/following{/other_user}",
        "gists_url": "https://api.github.com/users/chrisjcorbin/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/chrisjcorbin/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/chrisjcorbin/subscriptions",
        "organizations_url": "https://api.github.com/users/chrisjcorbin/orgs",
        "repos_url": "https://api.github.com/users/chrisjcorbin/repos",
        "events_url": "https://api.github.com/users/chrisjcorbin/events{/privacy}",
        "received_events_url": "https://api.github.com/users/chrisjcorbin/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "ajg7",
        "id": 49355730,
        "node_id": "MDQ6VXNlcjQ5MzU1NzMw",
        "avatar_url": "https://avatars2.githubusercontent.com/u/49355730?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ajg7",
        "html_url": "https://github.com/ajg7",
        "followers_url": "https://api.github.com/users/ajg7/followers",
        "following_url": "https://api.github.com/users/ajg7/following{/other_user}",
        "gists_url": "https://api.github.com/users/ajg7/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ajg7/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ajg7/subscriptions",
        "organizations_url": "https://api.github.com/users/ajg7/orgs",
        "repos_url": "https://api.github.com/users/ajg7/repos",
        "events_url": "https://api.github.com/users/ajg7/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ajg7/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "saljahmi",
        "id": 67301971,
        "node_id": "MDQ6VXNlcjY3MzAxOTcx",
        "avatar_url": "https://avatars1.githubusercontent.com/u/67301971?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/saljahmi",
        "html_url": "https://github.com/saljahmi",
        "followers_url": "https://api.github.com/users/saljahmi/followers",
        "following_url": "https://api.github.com/users/saljahmi/following{/other_user}",
        "gists_url": "https://api.github.com/users/saljahmi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/saljahmi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/saljahmi/subscriptions",
        "organizations_url": "https://api.github.com/users/saljahmi/orgs",
        "repos_url": "https://api.github.com/users/saljahmi/repos",
        "events_url": "https://api.github.com/users/saljahmi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/saljahmi/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "Cory-Thomas",
        "id": 29168407,
        "node_id": "MDQ6VXNlcjI5MTY4NDA3",
        "avatar_url": "https://avatars0.githubusercontent.com/u/29168407?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Cory-Thomas",
        "html_url": "https://github.com/Cory-Thomas",
        "followers_url": "https://api.github.com/users/Cory-Thomas/followers",
        "following_url": "https://api.github.com/users/Cory-Thomas/following{/other_user}",
        "gists_url": "https://api.github.com/users/Cory-Thomas/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Cory-Thomas/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Cory-Thomas/subscriptions",
        "organizations_url": "https://api.github.com/users/Cory-Thomas/orgs",
        "repos_url": "https://api.github.com/users/Cory-Thomas/repos",
        "events_url": "https://api.github.com/users/Cory-Thomas/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Cory-Thomas/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "sekotszs",
        "id": 60678391,
        "node_id": "MDQ6VXNlcjYwNjc4Mzkx",
        "avatar_url": "https://avatars2.githubusercontent.com/u/60678391?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/sekotszs",
        "html_url": "https://github.com/sekotszs",
        "followers_url": "https://api.github.com/users/sekotszs/followers",
        "following_url": "https://api.github.com/users/sekotszs/following{/other_user}",
        "gists_url": "https://api.github.com/users/sekotszs/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/sekotszs/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/sekotszs/subscriptions",
        "organizations_url": "https://api.github.com/users/sekotszs/orgs",
        "repos_url": "https://api.github.com/users/sekotszs/repos",
        "events_url": "https://api.github.com/users/sekotszs/events{/privacy}",
        "received_events_url": "https://api.github.com/users/sekotszs/received_events",
        "type": "User",
        "site_admin": false
    }
]

const gitUser = {
    "login": "thomasjk0831",
    "id": 67961239,
    "node_id": "MDQ6VXNlcjY3OTYxMjM5",
    "avatar_url": "https://avatars3.githubusercontent.com/u/67961239?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/thomasjk0831",
    "html_url": "https://github.com/thomasjk0831",
    "followers_url": "https://api.github.com/users/thomasjk0831/followers",
    "following_url": "https://api.github.com/users/thomasjk0831/following{/other_user}",
    "gists_url": "https://api.github.com/users/thomasjk0831/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/thomasjk0831/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/thomasjk0831/subscriptions",
    "organizations_url": "https://api.github.com/users/thomasjk0831/orgs",
    "repos_url": "https://api.github.com/users/thomasjk0831/repos",
    "events_url": "https://api.github.com/users/thomasjk0831/events{/privacy}",
    "received_events_url": "https://api.github.com/users/thomasjk0831/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Thomas Kim",
    "company": null,
    "blog": "",
    "location": "Florida",
    "email": null,
    "hireable": null,
    "bio": "I am a full-stack web development student",
    "twitter_username": null,
    "public_repos": 38,
    "public_gists": 0,
    "followers": 8,
    "following": 22,
    "created_at": "2020-07-07T12:50:59Z",
    "updated_at": "2020-09-01T15:21:56Z"
}

export {gitUser, gitFollowers}